#!/bin/sh /etc/rc.common
START=99
STOP=10

start() {
	enable=`ps | grep serverchan/serverchan | grep -v "grep" | awk '{print $1}'`
	if [ ! -z "$enable" ]; then
		restart
	else
		/usr/bin/serverchan/serverchan &
	fi
	echo "serverchan is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/serverchan/serverchan"` 2>/dev/null
	echo "serverchan exit ..."
}

restart(){
	stop
	sleep 2
	start
	echo "restarted."
}